- hosts: localhost
  gather_facts: false
  tasks:
    - name: Show encrypted ansible vault fact
      ansible.builtin.debug:
        msg: "The secret is: {{ my_secret }}"

    - name: Deploy secret to kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ansible-vault
            namespace: clt2025
          data:
            secret: "{{ my_secret | b64encode }}"
