- hosts: localhost
  tasks:
    - name: Deploy secret to kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ansible
            namespace: clt2025
          data:
            secret: "{{ kubernetes_secret | b64encode }}"
