apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-with-vault
  namespace: clt2025
  labels:
    app.kubernetes.io/name: simple-app-with-vault
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-app-with-vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-app-with-vault
    spec:
      containers:
        - name: http-echo
          image: docker.io/hashicorp/http-echo
          env:
            - name: ECHO_TEXT
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: my_secret
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-with-vault
  namespace: clt2025
spec:
  selector:
    app.kubernetes.io/name: simple-app-with-vault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-with-vault
  namespace: clt2025
spec:
  rules:
    - host: app.demo.local
      http:
        paths:
          - path: /vault
            pathType: Exact
            backend:
              service:
                name: simple-app-with-vault
                port:
                  number: 80
