# Based on vault operator tutorial
# https://github.com/hashicorp-education/learn-vault-secrets-operator/blob/main/vault/static-secret.yaml

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: simple-app-with-vault
  namespace: clt2025
spec:
  type: kv-v2
  # mount path
  mount: clt2025
  # path of the secret
  path: kubernetes
  # dest k8s secret
  destination:
    name: vault-secret
    create: true
  # static secret refresh interval
  refreshAfter: 3s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
  # Restart deployment after secret changes
  rolloutRestartTargets:
    - kind: Deployment
      name: simple-app-with-vault
