# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.box = "generic/ubuntu2204"

  # Data
  config.vm.synced_folder ".", "/vagrant_data",
    type: "rsync",
    rsync__exclude: [
      ".git/.*",
      "terraform/.terraform/",
      "terraform/.terraform.lock.hcl",
      ".vagrant/.*",
    ]

  config.vm.provider "libvirt" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Enable serial console
    systemctl enable --now serial-getty@ttyS0.service

    cd /vagrant_data
    # Install k3s
    scripts/install-k3s.sh
    # Install services
    scripts/install-sealed-secrets.sh
    scripts/install-vault.sh
    # Prepare secrets
    scripts/prepare-ansible-vault.sh
    scripts/prepare-sealed-secrets.sh
    scripts/prepare-sops.sh
    scripts/prepare-vault.sh
    # Run all demo examples
    scripts/run-ansible.sh
    scripts/run-kubernetes.sh
    scripts/run-terraform.sh
  SHELL
end
